public class Primitivedata_Assignment {
    public void primitiveDataAssignment() {
ID accountId = '0018d00000KVDdEAAX';
system.debug('ID number is ' + accountId);

string nmbrBelongs = 'The following Id belongs to Edge Communication.';
system.debug(nmbrBelongs);

Boolean isTrue = true;
system.debug('Id number contains 18 digits? ' + isTrue);

system.debug('ID number is ' + accountId + nmbrBelongs + 'ID number contains 18 digits ');
    }
}
